### ISSUE TITLE
Could you give the .apk ?

### ISSUE THREAD

**Issue by tomdereub** [DorianScholz/OpenLibre#2]
Hi,
I'm very interested to test this app, but I don't know how to build it. Is it possible for you to give the .apk already built ?
And what about putting it on F-droid ?
Thanks for your work.

**Comment by DorianScholz** [comment]
Hi,
thanks for your interest in the app.
But be warned, the OpenLibre app does not give you the same values as the original Libre reader or app, since it does not use their proprietary prediction algorithm...
The releases are available on github:
https://github.com/DorianScholz/OpenLibre/releases
Cheers
